#os: Visual Studio 2015

environment:
  global:

    # HDF_DIR: "C:/Program Files (x86)/HDF_Group/HDF5/1.8.17/lib"
    BOOST_ROOT: C:\Libraries\boost_1_67_0

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "27"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "27"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "36"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "36"
      PYTHON_ARCH: "64"

# init:
#   - cmd: cmake --version

install:
  - set ROOTPATH=%cd%
  - echo %ROOTPATH%
  - ls

  - git submodule update --init --recursive

  # Install Python module(s)
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade pip"
  - if "%PYTHON_VERSION%" == "27" python -m pip install cython
  - if "%PYTHON_VERSION%" == "36" python -m pip install Cython --install-option="--no-cython-compile"

  - md build
  - cd build

  # install hdf5
  - md HDF5
  - cd HDF5
  - if "%PYTHON_VERSION%" == "27" if "%PYTHON_ARCH%" == "32" curl -LvkO https://anaconda.org/anaconda/hdf5/1.8.17/download/win-32/hdf5-1.8.17-vc9_0.tar.bz2
  - if "%PYTHON_VERSION%" == "27" if "%PYTHON_ARCH%" == "64" curl -LvkO https://anaconda.org/anaconda/hdf5/1.8.17/download/win-64/hdf5-1.8.17-vc9_0.tar.bz2
  - if "%PYTHON_VERSION%" == "27" 7z x -y hdf5-1.8.17-vc9_0.tar.bz2
  - if "%PYTHON_VERSION%" == "27" 7z x -y hdf5-1.8.17-vc9_0.tar
  - if "%PYTHON_VERSION%" == "36" if "%PYTHON_ARCH%" == "32" curl -LvkO https://anaconda.org/anaconda/hdf5/1.8.17/download/win-32/hdf5-1.8.17-vc14_0.tar.bz2
  - if "%PYTHON_VERSION%" == "36" if "%PYTHON_ARCH%" == "64" curl -LvkO https://anaconda.org/anaconda/hdf5/1.8.17/download/win-64/hdf5-1.8.17-vc14_0.tar.bz2
  - if "%PYTHON_VERSION%" == "36" 7z x -y hdf5-1.8.17-vc14_0.tar.bz2
  - if "%PYTHON_VERSION%" == "36" 7z x -y hdf5-1.8.17-vc14_0.tar
  - set "HDF5PATH=C:/Program Files (x86)/HDF_Group/HDF5/1.8.17"
  - md "%HDF5PATH%"
  - xcopy Library "%HDF5PATH%" /s /e /y
  - ls "%HDF5PATH%"
  - cd ..

  # install stdint
  - if "%PYTHON_VERSION%" == "27" curl -O http://ftp.vector.co.jp/43/28/2114/stdint-20070624.zip
  - if "%PYTHON_VERSION%" == "27" unzip stdint-20070624.zip
  - if "%PYTHON_VERSION%" == "27" set "STDINTPATH=%ROOTPATH%/build/stdint-20070624"
  - if "%PYTHON_VERSION%" == "27" ls %STDINTPATH%

  # install gsl for build_ext
  - if "%PYTHON_VERSION%" == "27" curl -O http://r2d3.geldreich.net/downloads/gsl-1.13-windows-binaries.zip
  - if "%PYTHON_VERSION%" == "27" unzip gsl-1.13-windows-binaries.zip
  # - if "%PYTHON_VERSION%" == "27" cmake -G "Visual Studio 9 2008" -D CMAKE_CXX_FLAGS_RELEASE="/MD" -D CMAKE_CXX_FLAGS_DEBUG="/MDd" -D CMAKE_C_FLAGS_RELEASE="/MD" -D CMAKE_C_FLAGS_DEBUG="/MDd" .
  # - if "%PYTHON_VERSION%" == "27" msbuild GSL.sln /p:Configuration=Release /toolsversion:3.5
  - if "%PYTHON_VERSION%" == "36" git clone git://github.com/ampl/gsl.git
  - if "%PYTHON_VERSION%" == "36" cd gsl
  - if "%PYTHON_VERSION%" == "36" if "%PYTHON_ARCH%" == "32" cmake -G "Visual Studio 14 2015" -D CMAKE_CXX_FLAGS_RELEASE="/MD" -D CMAKE_CXX_FLAGS_DEBUG="/MDd" -D CMAKE_C_FLAGS_RELEASE="/MD" -D CMAKE_C_FLAGS_DEBUG="/MDd" .
  - if "%PYTHON_VERSION%" == "36" if "%PYTHON_ARCH%" == "64" cmake -G "Visual Studio 14 2015 Win64" -D CMAKE_CXX_FLAGS_RELEASE="/MD" -D CMAKE_CXX_FLAGS_DEBUG="/MDd" -D CMAKE_C_FLAGS_RELEASE="/MD" -D CMAKE_C_FLAGS_DEBUG="/MDd" .
  - if "%PYTHON_VERSION%" == "36" msbuild GSL.sln /p:Configuration=Release
  - if "%PYTHON_VERSION%" == "36" cd ..
  - set "GSLPATH=%ROOTPATH%/build/gsl"
  - ls %GSLPATH%

  # configure ecell4
  - cd %ROOTPATH%/build
  - if "%PYTHON_VERSION%" == "27" if "%PYTHON_ARCH%" == "32" cmake -G "Visual Studio 9 2008" -D CMAKE_CXX_FLAGS_RELEASE="/MT" -D CMAKE_CXX_FLAGS_DEBUG="/MTd" -DBOOST_REGEX_LIBRARIES=%BOOST_ROOT%/libs -DBoost_INCLUDE_DIR=%BOOST_ROOT% -DGSL_INCLUDE_DIR=%GSLPATH%/include -DGSL_CBLAS_LIBRARIES=%GSLPATH%/lib -DGSL_LIBRARIES=%GSLPATH%/lib -DNO_SHARED:BOOL=1 -DNO_BESSEL_TABLE:BOOL=1 ..
  - if "%PYTHON_VERSION%" == "27" if "%PYTHON_ARCH%" == "64" cmake -G "Visual Studio 9 2008 Win64" -D CMAKE_CXX_FLAGS_RELEASE="/MT" -D CMAKE_CXX_FLAGS_DEBUG="/MTd" -DBOOST_REGEX_LIBRARIES=%BOOST_ROOT%/libs -DBoost_INCLUDE_DIR=%BOOST_ROOT% -DGSL_INCLUDE_DIR=%GSLPATH%/include -DGSL_CBLAS_LIBRARIES=%GSLPATH%/lib -DGSL_LIBRARIES=%GSLPATH%/lib -DNO_SHARED:BOOL=1 -DNO_BESSEL_TABLE:BOOL=1 ..
  - if "%PYTHON_VERSION%" == "36" if "%PYTHON_ARCH%" == "32" cmake -G "Visual Studio 14 2015" -D CMAKE_CXX_FLAGS_RELEASE="/MD" -D CMAKE_CXX_FLAGS_DEBUG="/MDd" -D CMAKE_C_FLAGS_DEBUG="/MDd" -DBoost_INCLUDE_DIR=%BOOST_ROOT% -DGSL_INCLUDE_DIR=%GSLPATH% -DGSL_CBLAS_LIBRARIES=%GSLPATH%/Release -DGSL_LIBRARIES=%GSLPATH%/Release -DNO_SHARED:BOOL=1 -DNO_BESSEL_TABLE:BOOL=1 ..
  - if "%PYTHON_VERSION%" == "36" if "%PYTHON_ARCH%" == "64" cmake -G "Visual Studio 14 2015 Win64" -D CMAKE_CXX_FLAGS_RELEASE="/MD" -D CMAKE_CXX_FLAGS_DEBUG="/MDd" -D CMAKE_C_FLAGS_DEBUG="/MDd" -DBoost_INCLUDE_DIR=%BOOST_ROOT% -DGSL_INCLUDE_DIR=%GSLPATH% -DGSL_CBLAS_LIBRARIES=%GSLPATH%/Release -DGSL_LIBRARIES=%GSLPATH%/Release -DNO_SHARED:BOOL=1 -DNO_BESSEL_TABLE:BOOL=1 ..
  - cd %ROOTPATH%\build\ecell4\core
  - type config.h
  - cd %ROOTPATH%\build\greens_functions
  - type config.h

  - cd %ROOTPATH%/build
  - ls

  # Build Python module
  - cd %ROOTPATH%/build/python
  - if "%PYTHON_VERSION%" == "27" python setup.py build_ext -I"%HDF5PATH%\include";%BOOST_ROOT%;%ROOTPATH%;%STDINTPATH%;%GSLPATH%/include -L%GSLPATH%/lib;"%HDF5PATH%\lib"
  - if "%PYTHON_VERSION%" == "36" python setup.py build_ext -I"%HDF5PATH%\include";%BOOST_ROOT%;%GSLPATH% -L%GSLPATH%/Release;"%HDF5PATH%\lib"
  - ls
  # - "pip install wheel"
  # - "python setup.py bdist_wheel -v"

# # test_script:
# #   - "build.cmd %PYTHON%\\python.exe setup.py test"

build: false

branches:
  only:
    - master
    - conda

# artifacts:
#   # bdist_wheel puts your built wheel in the dist directory
#   - path: python/dist/*
# 
# notifications:
#   - provider: Slack
#     auth_token:
#       secure: xoxp-2152083718-2152083720-57117007011-a566bc1aa4
#     channel: '#github'
